<a href="https://colab.research.google.com/github/Divya28092005/Data_Science_Lab/blob/main/5ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Filtering Data: Selecting Iris-setosa Species

Let's filter the dataset to show only the records for the 'Iris-setosa' species. This demonstrates selecting specific rows based on a condition using Boolean indexing.

In [6]:
iris_setosa = df[df['species'] == 'Iris-setosa']
print("Filtered data for Iris-setosa species:")
display(iris_setosa.head())

Filtered data for Iris-setosa species:

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
import zipfile
import pandas as pd
import numpy as np

# Unzip the file
with zipfile.ZipFile('/content/iris.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

# Let's list the files to be sure.
import os
# The output shows 'iris.data' is the data file.
# The Iris dataset typically has no header and needs specific column names.

file_name = 'iris.data'
file_path = f'/content/{file_name}'

if os.path.exists(file_path):
    # Define column names based on the Iris dataset description
    column_names = [
        'sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'
    ]
    df = pd.read_csv(file_path, header=None, names=column_names)
    print("Dataset loaded successfully!")
    display(df.head())
else:
    print(f"Could not find the expected file: {file_name}. Please check the contents of the zip file.")

Dataset loaded successfully!

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [8]:
import zipfile
import pandas as pd
import numpy as np

# Unzip the file
with zipfile.ZipFile('/content/iris.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

# Let's list the files to be sure.
import os
# The output shows 'iris.data' is the data file.
# The Iris dataset typically has no header and needs specific column names.

file_name = 'iris.data'
file_path = f'/content/{file_name}'

if os.path.exists(file_path):
    # Define column names based on the Iris dataset description
    column_names = [
        'sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'
    ]
    df = pd.read_csv(file_path, header=None, names=column_names)
    print("Dataset loaded successfully!")
    display(df.head())
else:
    print(f"Could not find the expected file: {file_name}. Please check the contents of the zip file.")

Dataset loaded successfully!

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Now that we have loaded the dataset, let's get a general overview of its structure and summary statistics.

In [7]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000